const products = [
  // best-seller products

  {
    id: 0.1,
    name: "Women's 'Desk-to-Dinner' Cotton Stretch Formal Shirt (Button Down | Regular Fit | Stylish | Office-wear)",
    slug: "red-chief-genuine-leather-derby-lace-up-office-shirt",

    description:
      "It features smart cuffs on the sleeves that effortlessly scrunch up and stay securely in place. The front placket includes a discreet",
    discount: 30,
    price: 99.99,
    listPrice: 69.99,

    images: [
      "https://m.media-amazon.com/images/I/61eZiSLbBpL._SX522_.jpg",
      "https://m.media-amazon.com/images/I/71rbrJS2RjL._SX522_.jpg",
    ],
    gender: "Women",
    category: "Shirts",
    brand: "Shirk ",
    tags: ["best-seller"],
    isPublished: true,
    avgRating: 4.5,
    numReviews: 6,

    numSales: 9,
    countInStock: 60,
    colors: ["blue", "black"],
    sizes: ["S", "M", "L", "XL"],
    reviews: [],
  },
  {
    id: 0.2,
    name: "VERO MODA Women's Solid V-Neck Top |Day to Evening | Short Sleeves",
    slug: "red-chief-genuine-leather-derby-lace-up-office-shirt-1",

    description:
      "It features smart cuffs on the sleeves that effortlessly scrunch up and stay securely in place. The front placket includes a discreet",
    discount: 50,
    price: 99.99,
    listPrice: 49.99,

    images: [
      "https://m.media-amazon.com/images/I/61xP21EWQSL._SY679_.jpg",
      "https://m.media-amazon.com/images/I/61AxjZNo-RL._SY679_.jpg",
    ],
    gender: "Women",
    category: "Shirts",
    brand: "Shirk ",
    tags: ["best-seller"],
    isPublished: true,
    avgRating: 4.5,
    numReviews: 6,

    numSales: 9,
    countInStock: 60,
    colors: ["blue", "black"],
    sizes: ["S", "M", "L", "XL"],
    reviews: [],
  },
  {
    id: 0.3,
    name: "ABSOLUTE DEFENSE Oversize Tshirt Baggy for Women Girl Cotton Casual Stylish Latest Beige Black Blue Maroon White Lavender Pink Brown Peach 299 399 Under",
    slug: "lace-up-t-shirt-baggy-for-women-girl",

    description:
      "It features smart cuffs on the sleeves that effortlessly scrunch up and stay securely in place. The front placket includes a discreet",
    discount: 70,
    price: 199.99,
    listPrice: 79.99,

    images: [
      "https://m.media-amazon.com/images/I/51ZWI+GJMqL._SY606_.jpg",
      "https://m.media-amazon.com/images/I/41XEl03GaUL._SY606_.jpg",
    ],
    gender: "Women",
    category: "T-Shirts",
    brand: "Gucci ",
    tags: ["best-seller", "new-arrival"],
    isPublished: true,
    avgRating: 4.5,
    numReviews: 6,

    numSales: 9,
    countInStock: 60,
    colors: ["blue", "black"],
    sizes: ["S", "M", "L", "XL"],
    reviews: [],
  },
  {
    id: 0.000003,
    name: "FLEXIMAA Women's Cotton Plain Round Neck Half Sleeve Combo T-Shirt",
    slug: "lace-up-t-shirt-baggy-for-women-girl-t-shirts",

    description:
      "It features smart cuffs on the sleeves that effortlessly scrunch up and stay securely in place. The front placket includes a discreet",
    discount: 50,
    price: 89.99,
    listPrice: 0,

    images: [
      "https://m.media-amazon.com/images/I/71nir3RRdFL._SY679_.jpg",
      "https://m.media-amazon.com/images/I/8198bn3h8BL._SX679_.jpg",
    ],
    gender: "Women",
    category: "T-Shirts",
    brand: "Gucci ",
    tags: ["best-seller", "new-arrival"],
    isPublished: true,
    avgRating: 4.5,
    numReviews: 6,

    numSales: 9,
    countInStock: 60,
    colors: ["blue", "black"],
    sizes: ["S", "M", "L", "XL"],
    reviews: [],
  },
  {
    id: 0.00003,
    name: "Workout Quick Dry Gym Wear for Women Running Regular Fit T-Shirts for Women Short T Shirt",
    slug: "lace-up-t-shirt-baggy-for-women-girl-t-shirts-hhd",

    description:
      "It features smart cuffs on the sleeves that effortlessly scrunch up and stay securely in place. The front placket includes a discreet",
    discount: 50,
    price: 49.99,
    listPrice: 0,

    images: [
      "https://m.media-amazon.com/images/I/61lS4daJ4NL._SX679_.jpg",
      "https://m.media-amazon.com/images/I/61B22OjLnxL._SX679_.jpg",
    ],
    gender: "Women",
    category: "T-Shirts",
    brand: "Gucci ",
    tags: ["best-seller", "new-arrival"],
    isPublished: true,
    avgRating: 4.5,
    numReviews: 6,

    numSales: 9,
    countInStock: 60,
    colors: ["blue", "black"],
    sizes: ["S", "M", "L", "XL"],
    reviews: [],
  },
  {
    id: 0.03,
    name: "Nike Women's Cotton Checkered Regular Fit T-Shirt",
    slug: "nike-t-shirt-baggy-for-women-girl",

    description:
      "It features smart cuffs on the sleeves that effortlessly scrunch up and stay securely in place. The front placket includes a discreet",
    discount: 40,
    price: 49.99,
    listPrice: 0,

    images: [
      "https://m.media-amazon.com/images/I/61GZW38F9cL._SY679_.jpg",
      "https://m.media-amazon.com/images/I/61ntGj5YPNL._SY679_.jpg",
    ],
    gender: "Women",
    category: "T-Shirts",
    brand: "Nike ",
    tags: ["best-seller", "new-arrival"],
    isPublished: true,
    avgRating: 4.5,
    numReviews: 6,

    numSales: 9,
    countInStock: 60,
    colors: ["blue", "black"],
    sizes: ["S", "M", "L", "XL"],
    reviews: [],
  },
  {
    id: 2,
    name: "Lymio Men's Loose Shirt || Men's Shirt Pants || Denim Shirt || Baggy",
    slug: "lymio-mens-loose-shirt-mens-shirt-pants-denim-shirt-baggy",

    description:
      "Elevate your street cred by pairing these Baggy Oversized shirt with a graphic t-shirt and high-top sneakers. Roll up the cuffs for an added edge and throw on a bomber jacket to complete the look",
    discount: 80,
    price: 29.99,
    listPrice: 0,

    images: [
      "/images/shirts/shirts_p1-1.jpg",
      "/images/shirts/shirts_p1-2.jpg",
    ],
    gender: "Men",
    category: "Shirts",
    brand: "Levi's",
    tags: ["best-seller"],
    isPublished: true,
    avgRating: 4.5,
    numReviews: 6,

    numSales: 9,
    countInStock: 60,
    colors: ["blue", "dark-blue"],
    sizes: ["S", "M", "L", "XL"],
    reviews: [],
  },
  {
    id: 0.2,
    name: "Levi's Women's Slim Jeans",
    slug: "womens-lavis-jeans-mens-pants-denim-jeans-baggy",

    description:
      "Elevate your street cred by pairing these Baggy Oversized shirt with a graphic t-shirt and high-top sneakers. Roll up the cuffs for an added edge and throw on a bomber jacket to complete the look",
    discount: 90,
    price: 49.99,
    listPrice: 0,

    images: [
      "https://m.media-amazon.com/images/I/71ohU2gJzbL._SX522_.jpg",
      "https://m.media-amazon.com/images/I/71IP3JQ7ivL._SX522_.jpg",
    ],
    gender: "Women",
    category: "Jeans",
    brand: "Levi's",
    tags: ["best-seller", "new-arrival"],
    isPublished: true,
    avgRating: 4.5,
    numReviews: 6,

    numSales: 9,
    countInStock: 60,
    colors: ["blue", "dark-blue"],
    sizes: ["S", "M", "L", "XL"],
    reviews: [],
  },
  {
    id: 0.003,
    name: "Women's Slim Jeans Stylish",
    slug: "womens-lavis-jeans-mens-pants-denim-jeans",

    description:
      "Elevate your street cred by pairing these Baggy Oversized shirt with a graphic t-shirt and high-top sneakers. Roll up the cuffs for an added edge and throw on a bomber jacket to complete the look",
    discount: 70,
    price: 49.99,
    listPrice: 0,

    images: [
      "https://m.media-amazon.com/images/I/71ODjrA3j7L._SX522_.jpg",
      "https://m.media-amazon.com/images/I/81hhPteNpWL._SX522_.jpg",
    ],
    gender: "Women",
    category: "Jeans",
    brand: "Levi's",
    tags: ["best-seller", "new-arrival"],
    isPublished: true,
    avgRating: 4.5,
    numReviews: 6,

    numSales: 9,
    countInStock: 60,
    colors: ["blue", "dark-blue"],
    sizes: ["S", "M", "L", "XL"],
    reviews: [],
  },
  {
    id: 0.0003,
    name: "Miss Chase Women's Skinny Fit High/Mid Rise Regular Length Stretchable Denim Jeans",
    slug: "womens-lavis-jeans-mens-pants-denim-jeans-rise-regular",

    description:
      "Elevate your street cred by pairing these Baggy Oversized shirt with a graphic t-shirt and high-top sneakers. Roll up the cuffs for an added edge and throw on a bomber jacket to complete the look",
    discount: 55,
    price: 69.99,
    listPrice: 0,

    images: [
      "https://m.media-amazon.com/images/I/71LAQDR38NL._SY679_.jpg",
      "https://m.media-amazon.com/images/I/81P78nXN9PL._SY679_.jpg",
    ],
    gender: "Women",
    category: "Jeans",
    brand: "Levi's",
    tags: ["best-seller", "new-arrival"],
    isPublished: true,
    avgRating: 4.5,
    numReviews: 6,

    numSales: 9,
    countInStock: 60,
    colors: ["blue", "dark-blue"],
    sizes: ["S", "M", "L", "XL"],
    reviews: [],
  },
  {
    id: 1,
    name: "Red Chief Genuine Leather Derby Lace Up |Formal Watches for Men for Office | PU Sole | RC3506",
    slug: "red-chief-genuine-leather-derby-lace-up-formal-wathes-for-men-for-office-pu-sole-rc3506",

    description:
      "Elevate your street cred by pairing these Baggy Oversized Jeans with a graphic t-shirt and high-top sneakers. Roll up the cuffs for an added edge and throw on a bomber jacket to complete the look",
    discount: 45,
    price: 29.99,
    listPrice: 0,

    images: [
      "/images/watches/watches_p2-1.jpg",
      "/images/watches/watches_p2-2.jpg",
    ],
    gender: "Men",
    category: "Accessories",
    brand: "Omega ",
    tags: ["best-seller"],
    isPublished: true,
    avgRating: 4.5,
    numReviews: 6,

    numSales: 9,
    countInStock: 60,
    colors: ["blue", "dark-blue", "yellow"],
    sizes: ["S", "M", "L", "XL"],
    reviews: [],
  },
  {
    id: 3,
    name: "Maniac || Mens || Solid || Collared Neck || Full Sleeve || Knitted Shoes",
    slug: "maniac-mens-solid-collared-neck-full-sleeve-knitted-shoes",
    description:
      "Elevate your street cred by pairing these Baggy Oversized Jeans with a graphic shoes and high-top sneakers. Roll up the cuffs for an added edge and throw on a bomber jacket to complete the look",
    discount: 58,
    price: 29.99,
    listPrice: 0,

    images: ["/images/shoes/shoes_p3-1.jpg", "/images/shoes/shoes_p3-2.jpg"],
    gender: "Men",
    category: "Footwear",
    brand: "Adidas",
    tags: ["best-seller"],
    isPublished: true,
    avgRating: 4.5,
    numReviews: 6,

    numSales: 9,
    countInStock: 60,
    colors: ["blue", "dark-blue"],
    sizes: ["S", "M", "L", "XL"],
    reviews: [],
  },
  {
    id: 4,
    name: "Lymio Men's Fit T-Shirts || Men's T-Shirts || Denim T-Shirts || Baggy",
    slug: "lymio-mens-fit-t-shirts-mens-t-shirts-denim-t-shirts-baggy",

    description:
      "Elevate your street cred by pairing these Baggy Oversized Jeans with a graphic t-shirt and high-top sneakers. Roll up the cuffs for an added edge and throw on a bomber jacket to complete the look",
    discount: 79,
    price: 29.99,
    listPrice: 0,

    images: [
      "/images/t-shirts/t-shirts_p2-1.jpg",
      "/images/t-shirts/t-shirts_p2-2.jpg",
    ],
    gender: "Men",
    category: "T-Shirts",
    brand: "Polo",
    tags: ["best-seller"],
    isPublished: true,
    avgRating: 4.5,
    numReviews: 6,

    numSales: 9,
    countInStock: 60,
    colors: ["blue", "dark-blue"],
    sizes: ["S", "M", "L", "XL"],
    reviews: [],
  },
  {
    id: 5,
    name: "Lymio Men's Loose Jeans || Men's Jeans Pants || Denim Jeans || Baggy",
    slug: "lymio-mens-loose-jeans-mens-jeans-pants-denim-jeans-baggy",

    description:
      "Elevate your street cred by pairing these Baggy Oversized Jeans with a graphic t-shirt and high-top sneakers. Roll up the cuffs for an added edge and throw on a bomber jacket to complete the look",
    discount: 45,
    price: 29.99,
    listPrice: 0,

    images: ["/images/jeans/jeans_p1-1.jpg", "/images/jeans/jeans_p1-2.jpg"],
    gender: "Men",
    category: "Jeans",
    brand: "Levi's",
    tags: ["best-seller"],
    isPublished: true,
    avgRating: 4.5,
    numReviews: 6,

    numSales: 9,
    countInStock: 60,
    colors: ["blue", "dark-blue"],
    sizes: ["S", "M", "L", "XL"],
    reviews: [],
  },
  {
    id: 6,
    name: "Lymio Men's Loose shirts || Men's shirts Pants || Denim shirts || Baggy",
    slug: "lymio-mens-loose-shirts-mens-shirts-pants-denim-shirts-baggyss",

    description:
      "Elevate your street cred by pairing these Baggy Oversized shirts with a graphic t-shirt and high-top sneakers. Roll up the cuffs for an added edge and throw on a bomber jacket to complete the look",
    discount: 85,
    price: 29.99,
    listPrice: 0,

    images: [
      "/images/shirts/shirts_p1-1.jpg",
      "/images/shirts/shirts_p1-2.jpg",
    ],
    gender: "Men",
    category: "Shirts",
    brand: "Tom Ford",
    tags: ["best-seller"],
    isPublished: true,
    avgRating: 4.5,
    numReviews: 6,

    numSales: 9,
    countInStock: 60,
    colors: ["blue", "dark-blue"],
    sizes: ["S", "M", "L", "XL"],
    reviews: [],
  },
  {
    id: 7,
    name: "Lymio Men's Loose shirts || Men's t-shirts Pants || Baggy",
    slug: "lymio-mens-loose-shirts-mens-t-shirts-pants-baggy",

    description:
      "Elevate your street cred by pairing these Baggy Oversized shirts with a graphic t-shirt and high-top sneakers. Roll up the cuffs for an added edge and throw on a bomber jacket to complete the look",
    discount: 90,
    price: 29.99,
    listPrice: 0,

    images: [
      "/images/shirts/shirts_p2-1.jpg",
      "/images/shirts/shirts_p2-2.jpg",
    ],
    gender: "Men",
    category: "Shirts",
    brand: "Tom Ford",
    tags: ["best-seller"],
    isPublished: true,
    avgRating: 4.5,
    numReviews: 6,

    numSales: 9,
    countInStock: 60,
    colors: ["blue", "dark-blue"],
    sizes: ["S", "M", "L", "XL"],
    reviews: [],
  },
  // new-arrival products
  {
    id: 8,
    name: "Noble Monk Men's Solid Casual Shirt |Full Sleeve|Stylish Shirt for Men",
    slug: "noble-monk-mens-solid-casual-shirt-full-sleeve-stylish-shirt-for-men",

    description:
      "Elevate your street cred by pairing these Baggy Oversized Jeans with a graphic t-shirt and high-top sneakers. Roll up the cuffs for an added edge and throw on a bomber jacket to complete the look",
    discount: 79,
    price: 29.99,
    listPrice: 0,

    images: ["/images/shoes/shoes_p1-1.jpg", "/images/shoes/shoes_p1-2.jpg"],
    gender: "Men",
    category: "Footwear",
    brand: "Levi's",
    tags: ["new-arrival"],
    isPublished: true,
    avgRating: 4.5,
    numReviews: 6,

    numSales: 9,
    countInStock: 60,
    colors: ["blue", "dark-blue"],
    sizes: ["S", "M", "L", "XL"],
    reviews: [],
  },
  {
    id: 9,
    name: "Fossil Nate Chronograph Analog Black Dial Grey Band Men's Stainless Steel Watch ",
    slug: "fossil-nate-chronograph-analog-black-dial-grey-band-mens-stainless-steel-watch",

    description: "Fossil Nate JR1401 Chronograph Watch - For Men",
    discount: 80,
    price: 149.99,
    listPrice: 0,
    images: [
      "/images/watches/watches_p1-1.jpg",
      "/images/watches/watches_p1-2.jpg",
    ],
    gender: "Men",
    category: "Watches",
    brand: "Levi’s",
    tags: ["new-arrival", "best-seller"],
    isPublished: true,
    avgRating: 4.5,
    numReviews: 6,

    numSales: 16,
    countInStock: 20,
    colors: ["blue", "red", "green"],
    sizes: ["S", "M", "L", "XL"],
    reviews: [],
  },
  {
    id: 10,
    name: "Classic Moccasins Non-Lace Up Formal Shoes for Office, Party,Wedding | Dress Shoes",
    slug: "classic-moccasins-non-lace-up-formal-shoes-for-office-party-wedding-dress-shoes",

    description: "This is the description of product.",
    discount: 30,
    price: 129.99,
    listPrice: 0,
    images: ["/images/shoes/shoes_p3-1.jpg", "/images/shoes/shoes_p3-2.jpg"],
    gender: "Men",
    category: "Footwear",
    brand: "Levi’s",
    tags: ["new-arrival"],
    isPublished: true,
    avgRating: 4,
    numReviews: 6,

    numSales: 16,
    countInStock: 20,
    colors: ["blue", "red", "green"],
    sizes: ["S", "M", "L", "XL"],
    reviews: [],
  },
  {
    id: 11,
    name: "Centrino Mens 7957 Classic Moccasins Non-Lace Up Formal Shoes for Office, Party",
    slug: "centrino-mens-7957-classic-moccasins-non-lace-up-formal-shoes-for-office-party",
    description: "This is the description of product 1.",
    discount: 40,
    price: 149.99,
    listPrice: 0,
    images: ["/images/shoes/shoes_p2-1.jpg", "/images/shoes/shoes_p2-2.jpg"],
    gender: "Men",
    category: "Footwear",
    brand: "Levi’s",
    tags: ["new-arrival"],
    isPublished: true,
    avgRating: 4.5,
    numReviews: 6,

    numSales: 16,
    countInStock: 20,
    colors: ["blue", "red", "green"],
    sizes: ["S", "M", "L", "XL"],
    reviews: [],
  },
  {
    id: 12,
    name: "Symbol Premium Men's Slim Fit Stretchable Jeans | Casual Denim | Cotton Stretch ",
    slug: "symbol-premium-mens-slim-fit-stretchable-jeans-casual-denim-cotton-stretch",

    description:
      "Symbol Premium's easy stretch jeans feature 'Air-Lite' hollow fiber, providing a unique blend of style, comfort. A desirable choice for denim lovers seeking both fashion and functionality in their wardrobe",
    discount: 55,
    price: 149.99,
    listPrice: 0,
    images: ["/images/jeans/jeans_p1-1.jpg", "/images/jeans/jeans_p1-2.jpg"],
    gender: "Men",
    category: "Jeans",
    brand: "Levi’s",
    tags: ["new-arrival"],
    isPublished: true,
    avgRating: 4.5,
    numReviews: 6,

    numSales: 16,
    countInStock: 20,
    colors: ["blue", "red", "green"],
    sizes: ["S", "M", "L", "XL"],
    reviews: [],
  },
  {
    id: 13,
    name: "Ben Martin Men's Relaxed Fit Jeans",
    slug: "ben-martin-mens-relaxed-fit-jeans",

    description:
      "This Ben Martin casual denim jeans pant for men Durable and timeless look.AVAILABLE SIZE & COLOUR: This Ben Martin Mens Cotton Denim Jeans comes Range of sizes & Colors to suit different types. 40 Dark Blue, Light Blue, Brown, Green, Grey, Black & White. This Ben Martin Denim Jeans pant for Men is light weight breathable soft denim fabric. 1) Comfortable for all-day wear. 2) Casual and laid-back style. 3) 5 Basic Coin pockets for added functionality. 4) vailable in different washes and finishes.",
    discount: 60,
    price: 149.99,
    listPrice: 0,
    images: ["/images/jeans/jeans_p2-1.jpg", "/images/jeans/jeans_p2-2.jpg"],
    gender: "Men",
    category: "Jeans",
    brand: "Levi’s",
    tags: ["new-arrival"],
    isPublished: true,
    avgRating: 4.5,
    numReviews: 6,

    numSales: 16,
    countInStock: 20,
    colors: ["blue", "red", "green"],
    sizes: ["S", "M", "L", "XL"],
    reviews: [],
  },

  // today's deal products
  {
    id: 14,
    name: "Ben Martin Men's Regular Fit Stylish Stretchable 32 Size Brown Casusal Denim Jeans Pant for Men",
    slug: "ben-martin-mens-regular-fit-stylish-stretchable-32-size-brown-casual-denim-jeans-pant-for-men",
    description:
      "STRETCH COMFORT : These Ben Martin cotton denim casual jeans pant for men are constructed from a perfect blend of stretch-cotton fabric, which maximizes freedom of movement and ensures comfortable wear all day long.",
    discount: 30,
    price: 59.99,
    listPrice: 0,

    images: ["/images/jeans/jeans_p3-1.jpg", "/images/jeans/jeans_p3-2.jpg"],
    gender: "Men",
    category: "Jeans",
    brand: "Gucci",
    tags: ["today-deal"],
    isPublished: true,
    avgRating: 4.5,
    numReviews: 6,

    numSales: 13,
    countInStock: 40,
    colors: ["black", "white"],
    sizes: ["S", "M", "L", "XL"],
    reviews: [],
  },
  {
    id: 15,
    name: "Red Chief Genuine Leather Derby Lace Up |Formal Shoes for Men for Office | PU Sole | RC3506",
    slug: "lymio-polo-t-shirt-for-men-men-casual-t-shirt-polo-44-47",
    description:
      "Elevate your street cred by pairing these Baggy Oversized Jeans with a graphic t-shirt and high-top sneakers. Roll up the cuffs for an added edge and throw on a bomber jacket to complete the look",
    discount: 80,
    price: 29.99,
    listPrice: 0,

    images: ["/images/shoes/shoes_p2-1.jpg", "/images/shoes/shoes_p2-2.jpg"],
    gender: "Men",
    category: "Footwear",
    brand: "Puma",
    tags: ["today-deal"],
    isPublished: true,
    avgRating: 4.5,
    numReviews: 6,

    numSales: 9,
    countInStock: 60,
    colors: ["blue", "dark-blue"],
    sizes: ["S", "M", "L", "XL"],
    reviews: [],
  },
  {
    id: 16,
    name: "Lymio Men's Loose Jeans || Men's Jeans Pants || Denim Jeans || Baggy",
    slug: "lymio-polo-t-shirt-for-men-men-casual-t-shirt",

    description:
      "Elevate your street cred by pairing these Baggy Oversized Jeans with a graphic t-shirt and high-top sneakers. Roll up the cuffs for an added edge and throw on a bomber jacket to complete the look",
    discount: 80,
    price: 229.99,
    listPrice: 0,

    images: ["/images/jeans/jeans_p2-1.jpg", "/images/jeans/jeans_p2-2.jpg"],
    gender: "Men",
    category: "Jeans",
    brand: "Gucci",
    tags: ["today-deal"],
    isPublished: true,
    avgRating: 4.5,
    numReviews: 6,

    numSales: 9,
    countInStock: 60,
    colors: ["blue", "dark-blue"],
    sizes: ["S", "M", "L", "XL"],
    reviews: [],
  },
  {
    id: 17,
    name: "Lymio Polo T Shirt for Men || Men Casual T-Shirt (Polo 44-47)",
    slug: "Lymio Polo T Shirt for Men || Men Casual T-Shirt (Polo 44-47)",
    description:
      "Elevate your street cred by pairing these Baggy Oversized Jeans with a graphic t-shirt and high-top sneakers. Roll up the cuffs for an added edge and throw on a bomber jacket to complete the look",
    discount: 90,
    price: 329.99,
    listPrice: 0,

    images: [
      "/images/t-shirts/t-shirts_p1-1.jpg",
      "/images/t-shirts/t-shirts_p1-2.jpg",
    ],
    gender: "Men",
    category: "T-Shirts",
    brand: "Polo",
    tags: ["today-deal"],
    isPublished: true,
    avgRating: 4.5,
    numReviews: 6,

    numSales: 9,
    countInStock: 60,
    colors: ["blue", "dark-blue"],
    sizes: ["S", "M", "L", "XL"],
    reviews: [],
  },
  {
    id: 18,
    name: "Lymio Polo T Shirt for Men || Men Casual T-Shirt",
    slug: "Lymio Polo T Shirt for Men || Men Casual T-Shirt",

    description:
      "Elevate your street cred by pairing these Baggy Oversized Jeans with a graphic t-shirt and high-top sneakers. Roll up the cuffs for an added edge and throw on a bomber jacket to complete the look",
    discount: 20,
    price: 329.99,
    listPrice: 0,

    images: [
      "/images/t-shirts/t-shirts_p2-1.jpg",
      "/images/t-shirts/t-shirts_p3-2.jpg",
    ],
    gender: "Men",
    category: "T-Shirts",
    brand: "Polo",
    tags: ["today-deal"],
    isPublished: true,
    avgRating: 4.5,
    numReviews: 6,

    numSales: 9,
    countInStock: 60,
    colors: ["blue", "dark-blue"],
    sizes: ["S", "M", "L", "XL"],
    reviews: [],
  },
  {
    id: 19,
    name: "POLO Men's Wonder-14 T-Shirts (p-40-69)",
    slug: "POLO Men's Wonder-14 T-Shirts (p-40-69)",
    description:
      "Elevate your street cred by pairing these Baggy POLO Men's Wonder-13 Sports Running T-Shirts. High-top sneakers. Roll up the cuffs for an added edge and throw on a bomber jacket to complete the look",
    discount: 25,
    price: 99.99,
    listPrice: 0,

    images: [
      "/images/t-shirts/t-shirts_p3-1.jpg",
      "/images/t-shirts/t-shirts_p3-2.jpg",
    ],
    gender: "Men",
    category: "T-Shirts",
    brand: "Burberry",
    tags: ["today-deal"],
    isPublished: true,
    avgRating: 4.5,
    numReviews: 6,

    numSales: 9,
    countInStock: 60,
    colors: ["blue", "dark-blue"],
    sizes: ["S", "M", "L", "XL"],
    reviews: [],
  },

  // featured products
  {
    id: 20,
    name: "Urbano Fashion Men's Cotton Full Sleeve Regular Fit Casual Solid Shirt",
    slug: "Urbano Fashion Men's Cotton Full Sleeve Regular Fit Casual Solid Shirt",

    description:
      "Elevate your street cred by pairing these Baggy Oversized Jeans with a graphic t-shirt and high-top sneakers. Roll up the cuffs for an added edge and throw on a bomber jacket to complete the look",
    discount: 56,
    price: 329.99,
    listPrice: 0,

    images: [
      "/images/shirts/shirts_p1-1.jpg",
      "/images/shirts/shirts_p1-2.jpg",
    ],
    gender: "Men",
    category: "Shirts",
    brand: "Levi's",
    tags: ["featured", "best-seller"],
    isPublished: true,
    avgRating: 4.5,
    numReviews: 6,

    numSales: 9,
    countInStock: 60,
    colors: ["blue", "dark-blue"],
    sizes: ["S", "M", "L", "XL"],
    reviews: [],
  },
  {
    id: 21,
    name: "Urbano Fashion Men's Cotton Full Sleeve Regular Fit Casual Solid Shirt",
    slug: "watches-one-for-men",

    description:
      "Elevate your street cred by pairing these Baggy Oversized Jeans with a graphic t-shirt and high-top sneakers. Roll up the cuffs for an added edge and throw on a bomber jacket to complete the look",
    discount: 59,
    price: 329.99,
    listPrice: 0,

    images: [
      "/images/watches/watches_p2-1.jpg",
      "/images/watches/watches_p2-2.jpg",
    ],
    gender: "Men",
    category: "Watches",
    brand: "Breitling ",
    tags: ["featured", "best-seller"],
    isPublished: true,
    avgRating: 4.5,
    numReviews: 6,

    numSales: 9,
    countInStock: 60,
    colors: ["blue", "dark-blue"],
    sizes: ["S", "M", "L", "XL"],
    reviews: [],
  },
  {
    id: 22,
    name: "ASIAN Men's Wonder-13 Sports Running Shoes",
    slug: "ASIAN Men's Wonder-13 Sports Running Shoes",

    description:
      "Elevate your street cred by pairing these Baggy ASIAN Men's Wonder-13 Sports Running Shoe. High-top sneakers. Roll up the cuffs for an added edge and throw on a bomber jacket to complete the look",
    discount: 68,
    price: 329.99,
    listPrice: 0,

    images: ["/images/shoes/shoes_p4-1.jpg", "/images/shoes/shoes_p4-2.jpg"],
    gender: "Men",
    category: "Footwear",
    brand: "Nike",
    tags: ["featured"],
    isPublished: true,
    avgRating: 4.5,
    numReviews: 6,

    numSales: 9,
    countInStock: 60,
    colors: ["blue", "dark-blue"],
    sizes: ["S", "M", "L", "XL"],
    reviews: [],
  },
  {
    id: 23,
    name: "ASIAN Men's Wonder-13 Sports Running Shoes",
    slug: "ASIAN Men's Wonder-13 Sports Running Shoes",

    description:
      "Elevate your street cred by pairing these Baggy ASIAN Men's Wonder-13 Sports Running Shoe. High-top sneakers. Roll up the cuffs for an added edge and throw on a bomber jacket to complete the look",
    discount: 68,
    price: 329.99,
    listPrice: 0,

    images: [
      "/images/shirts/shirts_p2-1.jpg",
      "/images/shirts/shirts_p2-2.jpg",
    ],
    gender: "Men",
    category: "Shirts",
    brand: "Burberry",
    tags: ["featured"],
    isPublished: true,
    avgRating: 4.5,
    numReviews: 6,

    numSales: 9,
    countInStock: 60,
    colors: ["blue", "dark-blue"],
    sizes: ["S", "M", "L", "XL"],
    reviews: [],
  },
  {
    id: 24,
    name: "POLO Men's Wonder-13 T-Shirts",
    slug: "POLO Men's Wonder-13 T-Shirts",

    description:
      "Elevate your street cred by pairing these Baggy POLO Men's Wonder-13 Sports Running T-Shirts. High-top sneakers. Roll up the cuffs for an added edge and throw on a bomber jacket to complete the look",
    discount: 50,
    price: 329.99,
    listPrice: 0,

    images: [
      "/images/t-shirts/t-shirts_p4-1.jpg",
      "/images/t-shirts/t-shirts_p4-2.jpg",
    ],
    gender: "Men",
    category: "T-Shirts",
    brand: "Burberry",
    tags: ["featured"],
    isPublished: true,
    avgRating: 4.5,
    numReviews: 6,

    numSales: 9,
    countInStock: 60,
    colors: ["blue", "dark-blue"],
    sizes: ["S", "M", "L", "XL"],
    reviews: [],
  },
  {
    id: 25,
    name: "POLO Men's Wonder-14 T-Shirts (p-40-69)",
    slug: "POLO Men's Wonder-14 T-Shirts (p-40-69)",
    description:
      "Elevate your street cred by pairing these Baggy POLO Men's Wonder-13 Sports Running T-Shirts. High-top sneakers. Roll up the cuffs for an added edge and throw on a bomber jacket to complete the look",
    discount: 40,
    price: 99.99,
    listPrice: 0,

    images: [
      "/images/t-shirts/t-shirts_p3-1.jpg",
      "/images/t-shirts/t-shirts_p3-2.jpg",
    ],
    gender: "Men",
    category: "T-Shirts",
    brand: "Burberry",
    tags: ["featured"],
    isPublished: true,
    avgRating: 4.5,
    numReviews: 6,

    numSales: 9,
    countInStock: 60,
    colors: ["blue", "dark-blue"],
    sizes: ["S", "M", "L", "XL"],
    reviews: [],
  },
  {
    id: 101,
    name: "Symbol Premium Women's 'Desk to Dinner' Slingback Pumps",
    slug: "elegant-stiletto-heels-women",
    description:
      "Step into sophistication with these elegant stiletto heels, perfect for evening events or formal wear.",
    discount: 60,
    price: 49.99,
    listPrice: 79.99,
    images: [
      "https://m.media-amazon.com/images/I/71oQDjYj8WL._SY675_.jpg",
      "https://m.media-amazon.com/images/I/71ze+WIO75L._SY675_.jpg",
    ],
    gender: "Women",
    category: "Footwear",
    brand: "Bella Vogue",
    tags: ["best-seller", "heels"],
    isPublished: true,
    avgRating: 4.8,
    numReviews: 18,
    numSales: 42,
    countInStock: 25,
    colors: ["black", "red", "nude"],
    sizes: ["S", "M", "L"],
    gender: "Women",
    reviews: [],
  },
  {
    id: 1001,
    name: "Elegant Stiletto Heels",
    slug: "elegant-stiletto-heels-women-heels",
    description:
      "Step into sophistication with these elegant stiletto heels, perfect for evening events or formal wear.",
    discount: 70,
    price: 79.99,
    listPrice: 99.99,
    images: [
      "https://m.media-amazon.com/images/I/71kZwI4bP2L._SY675_.jpg",
      "https://m.media-amazon.com/images/I/711P1VE-4EL._SY675_.jpg",
    ],

    category: "Footwear",
    brand: "Bella Vogue",
    tags: ["best-seller", "heels"],
    isPublished: true,
    avgRating: 4.8,
    numReviews: 18,
    numSales: 42,
    countInStock: 25,
    colors: ["black", "red", "nude"],
    sizes: ["S", "M", "L"],
    reviews: [],
    gender: "Women",
  },
  {
    id: 102,
    name: "Vendoz Women Stylish Cream Flat Sandals",
    slug: "casual-white-flats-women",
    description:
      "Stay comfortable and stylish with these minimalist flats made for everyday walking.",
    discount: 80,
    price: 34.99,
    listPrice: 49.99,
    images: [
      "https://m.media-amazon.com/images/I/61yZsOC22AL._SY500_.jpg",
      "https://m.media-amazon.com/images/I/51ZuIZhmfhL._SY500_.jpg",
    ],
    gender: "Women",
    category: "Footwear",
    brand: "UrbanFeet",
    tags: ["flat", "everyday"],
    isPublished: true,
    avgRating: 4.6,
    numReviews: 12,
    numSales: 33,
    countInStock: 40,
    colors: ["white", "beige"],
    sizes: ["M", "L", "XL"],
    gender: "Women",
    reviews: [],
  },
  {
    id: 1002,
    name: "Vendoz Women Stylish Cream Flat Sandals",
    slug: "casual-white-flats-women-flats",
    description:
      "Stay comfortable and stylish with these minimalist flats made for everyday walking.",
    discount: 50,
    price: 34.99,
    listPrice: 49.99,
    images: [
      "https://m.media-amazon.com/images/I/51BdzBgSVbL._SY675_.jpg",
      "https://m.media-amazon.com/images/I/61f1ydF7whL._SY675_.jpg",
    ],
    gender: "Women",
    category: "Footwear",
    brand: "UrbanFeet",
    tags: ["flat", "everyday", "best-seller"],
    isPublished: true,
    avgRating: 4.6,
    numReviews: 12,
    numSales: 33,
    countInStock: 40,
    colors: ["white", "beige"],
    sizes: ["M", "L", "XL"],
    gender: "Women",
    reviews: [],
  },
  {
    id: 103,
    name: "Beach Vibe Sandals",
    slug: "beach-vibe-sandals-women-sandles",
    description:
      "Lightweight and breathable, these sandals are ideal for beach outings or casual summer days.",
    discount: 70,
    price: 27.99,
    listPrice: 39.99,
    images: [
      "https://m.media-amazon.com/images/I/51lHLRorDPL._SY500_.jpg",
      "https://m.media-amazon.com/images/I/51bxzQP4O1L._SY500_.jpg",
    ],
    gender: "Women",
    category: "Footwear",
    brand: "SunWalk",
    tags: ["summer", "sandals"],
    isPublished: true,
    avgRating: 4.3,
    numReviews: 9,
    numSales: 21,
    countInStock: 36,
    colors: ["yellow"],
    sizes: ["S", "M", "L"],
    gender: "Women",
    reviews: [],
  },
  {
    id: 104,
    name: "Chunky White Sneakers",
    slug: "chunky-white-sneakers-women",
    description:
      "Add a modern twist to your streetwear style with these comfortable chunky sneakers.",
    discount: 79,
    price: 59.99,
    listPrice: 79.99,
    images: [
      "https://images.pexels.com/photos/2529148/pexels-photo-2529148.jpeg",
      "https://images.pexels.com/photos/1204464/pexels-photo-1204464.jpeg",
    ],
    gender: "Women",
    category: "Footwear",
    brand: "StepMax",
    tags: ["sneakers", "white"],
    isPublished: true,
    avgRating: 4.7,
    numReviews: 15,
    numSales: 37,
    countInStock: 50,
    colors: ["white", "gray"],
    sizes: ["M", "L", "XL"],
    reviews: [],
  },
  {
    id: 105,
    name: "Bacca Bucci Men Lace Up Sneaker Shoes",
    slug: "leather-ankle-boots-women-bucci-men-lace",
    description:
      "Made from genuine leather, these ankle boots combine elegance with durability for a chic look.",
    discount: 90,
    price: 89.99,
    listPrice: 119.99,
    images: [
      "https://m.media-amazon.com/images/I/419vnRwtJnL._SY625_.jpg",
      "https://m.media-amazon.com/images/I/61qyumEgw2L._SY675_.jpg",
    ],
    gender: "Women",
    category: "Footwear",
    brand: "TimberLane",
    tags: ["boots", "leather", "best-seller"],
    isPublished: true,
    avgRating: 4.9,
    numReviews: 22,
    numSales: 51,
    countInStock: 20,
    colors: ["brown", "black"],
    sizes: ["S", "M", "L"],
    gender: "Women",
    reviews: [],
  },

  {
    id: 106,
    name: "Beach Vibe Sandals",
    slug: "beach-vibe-sandals-women-fanssy",
    description:
      "Lightweight and breathable, these sandals are ideal for beach outings or casual summer days.",
    discount: 30,
    price: 27.99,
    listPrice: 39.99,
    images: [
      "https://m.media-amazon.com/images/I/71oFITJVMyL._SY695_.jpg",
      "https://m.media-amazon.com/images/I/71e6tMleftL._SY695_.jpg",
    ],
    gender: "Women",
    category: "Footwear",
    brand: "SunWalk",
    tags: ["summer", "sandals"],
    isPublished: true,
    avgRating: 4.3,
    numReviews: 9,
    numSales: 21,
    countInStock: 36,
    colors: ["tan", "yellow"],
    sizes: ["S", "M", "L"],
    gender: "Women",
    reviews: [],
  },
  {
    id: 107,
    name: "Symbol Premium Mens Smart Casual Flat Leather Sneakers",
    slug: "urban-edge-sneakers-women-casual",
    description:
      "Stylish and supportive sneakers perfect for urban explorers and casual outings.",
    discount: 80,
    price: 49.99,
    listPrice: 59.99,
    images: [
      "https://m.media-amazon.com/images/I/71z0J06321L._SY675_.jpg",
      "https://m.media-amazon.com/images/I/71sX2acqoXL._SY675_.jpg",
    ],
    gender: "Women",
    category: "Sneakers",
    brand: "StrideX",
    tags: ["sneakers", "casual"],
    isPublished: true,
    avgRating: 4.6,
    numReviews: 14,
    numSales: 33,
    countInStock: 40,
    colors: ["white", "pink"],
    sizes: ["S", "M", "L", "XL"],
    gender: "Women",
    reviews: [],
  },
  {
    id: 108,
    name: "TRASE Block Heels Sandals For Women, Sassy Stylish & Comfortable Footwear",
    slug: "elevate-block-heels-women-sandals-women",
    description:
      "Elegant block heels with a comfortable fit, ideal for work or evening outings.",
    discount: 40,
    price: 59.99,
    listPrice: 74.99,
    images: [
      "https://m.media-amazon.com/images/I/6159+SakRPL._SY500_.jpg",
      "https://m.media-amazon.com/images/I/61HWG-3wmBL._SY500_.jpg",
    ],
    gender: "Women",
    category: "Footwear",
    brand: "ChicLift",
    tags: ["heels", "formal", "best-seller"],
    isPublished: true,
    avgRating: 4.4,
    numReviews: 12,
    numSales: 28,
    countInStock: 25,
    colors: ["black", "beige"],
    sizes: ["M", "L", "XL"],
    gender: "Women",
    reviews: [],
  },
  {
    id: 109,
    name: "XE Looks Stylish & Comfortable Pencil Heel Fashion Bellies for Women",
    slug: "boho-canvas-flats-women-bellies-for-women",
    description:
      "Eco-friendly and ultra-light flats with a boho design for all-day comfort.",
    discount: 30,
    price: 22.99,
    listPrice: 34.99,
    images: [
      "https://m.media-amazon.com/images/I/713Pa9SyWKL._SY500_.jpg",
      "https://m.media-amazon.com/images/I/61Cmavzy24L._SY500_.jpg",
    ],
    gender: "Women",
    category: "Flats",
    brand: "GreenStep",
    tags: ["eco", "flats", "boho"],
    isPublished: true,
    avgRating: 4.1,
    numReviews: 8,
    numSales: 19,
    countInStock: 30,
    colors: ["brown", "cream"],
    sizes: ["S", "M", "L"],
    gender: "Women",
    reviews: [],
  },
  {
    id: 110,
    name: "Campus Women Ogl-13 Sneakers",
    slug: "street-vibe-platform-sneakers-women-campus",
    description:
      "Chunky platform sneakers for a bold fashion statement and ultimate comfort.",
    discount: 40,
    price: 64.99,
    listPrice: 89.99,
    images: [
      "https://m.media-amazon.com/images/I/61MZ4xj-gXL._SY575_.jpg",
      "https://m.media-amazon.com/images/I/61B876acE+L._SY575_.jpg",
    ],
    gender: "Women",
    category: "Sneakers",
    brand: "VoltWear",
    tags: ["platform", "trendy"],
    isPublished: true,
    avgRating: 4.7,
    numReviews: 16,
    numSales: 42,
    countInStock: 50,
    colors: ["white", "purple"],
    sizes: ["M", "L", "XL"],
    gender: "Women",
    reviews: [],
  },

  {
    id: 111,
    name: "Urban Trek Sandals",
    slug: "urban-trek-sandals-men",
    description:
      "Durable and stylish sandals ideal for outdoor adventures and summer wear.",
    discount: 20,
    price: 32.99,
    listPrice: 45.99,
    images: [
      "https://m.media-amazon.com/images/I/51xWMRRtdPL._SX500_.jpg",
      "https://m.media-amazon.com/images/I/71AHiOZHshL._SY500_.jpg",
    ],
    gender: "Women",
    category: "Footwear",
    brand: "TrailFlex",
    tags: ["outdoor", "sandals"],
    isPublished: true,
    avgRating: 4.5,
    numReviews: 11,
    numSales: 30,
    countInStock: 42,
    colors: ["brown", "black"],
    sizes: ["M", "L", "XL"],
    gender: "Men",
    reviews: [],
  },
  {
    id: 112,
    name: "Puma Men Galaxis Pro Running Shoe",
    slug: "runner-pro-sneakers-men",
    description:
      "High-performance running sneakers designed for comfort and breathability.",
    discount: 30,
    price: 58.49,
    listPrice: 69.99,
    images: [
      "https://m.media-amazon.com/images/I/51We0y6ETSL._SY625_.jpg",
      "https://m.media-amazon.com/images/I/41wQ9SDN71L._SY625_.jpg",
    ],
    gender: "Men",
    gender: "Men",
    category: "Footwear",
    brand: "Puma",
    tags: ["running", "fitness", "best-seller"],
    isPublished: true,
    avgRating: 4.6,
    numReviews: 15,
    numSales: 41,
    countInStock: 50,
    colors: ["Yellow", "white"],
    sizes: ["S", "M", "L", "XL"],
    gender: "Men",
    reviews: [],
  },
  {
    id: 113,
    name: "Casual Street Loafers",
    slug: "casual-street-loafers-men",
    description:
      "Smart-casual loafers that pair well with jeans or chinos for a relaxed urban look.",
    discount: 40,
    price: 39.99,
    listPrice: 49.99,
    images: [
      "https://images.pexels.com/photos/292999/pexels-photo-292999.jpeg",
      "https://images.pexels.com/photos/191829/pexels-photo-191829.jpeg",
    ],
    gender: "Men",
    category: "Footwear",
    brand: "UrbanStep",
    tags: ["casual", "loafers"],
    isPublished: true,
    avgRating: 4.2,
    numReviews: 7,
    numSales: 22,
    countInStock: 35,
    colors: ["navy", "grey"],
    sizes: ["M", "L", "XL"],
    gender: "Men",
    reviews: [],
  },
  {
    id: 114,
    name: "Office Classic Formal Shoes",
    slug: "office-classic-formal-shoes-men",
    description:
      "Polished leather formal shoes designed to complement any business or formal attire.",
    discount: 40,
    price: 74.99,
    listPrice: 89.99,
    images: [
      "https://images.pexels.com/photos/19090/pexels-photo.jpg",
      "https://images.pexels.com/photos/267320/pexels-photo-267320.jpeg",
    ],
    gender: "Men",
    category: "Footwear",
    brand: "EliteStep",
    tags: ["formal", "leather"],
    isPublished: true,
    avgRating: 4.7,
    numReviews: 18,
    numSales: 50,
    countInStock: 45,
    colors: ["black", "brown"],
    sizes: ["M", "L", "XL"],
    gender: "Men",
    reviews: [],
  },
  {
    id: 115,
    name: "Campus Men Crysta Pro Running Shoes",
    slug: "slip-on-canvas-sneakers-men",
    description:
      "Breathable and easy-to-wear canvas sneakers perfect for everyday errands.",
    discount: 70,
    price: 29.99,
    listPrice: 39.99,
    images: [
      "https://m.media-amazon.com/images/I/71VyVqTJetL._SY500_.jpg",
      "https://m.media-amazon.com/images/I/71BoKTLJmsL._SY500_.jpg",
    ],
    gender: "Men",
    category: "Footwear",
    brand: "EaseWear",
    tags: ["casual", "canvas", "today-deal"],
    isPublished: true,
    avgRating: 4.1,
    numReviews: 6,
    numSales: 17,
    countInStock: 28,
    colors: ["grey", "white"],
    sizes: ["S", "M", "L"],
    gender: "Men",
    reviews: [],
  },
  {
    id: 201,
    name: "YOHO Street Women’s Trendy Dual-Tone Casual Shoes",
    slug: "slip-on-canvas-sneakers-women-casual",
    description:
      "Breathable and easy-to-wear canvas sneakers perfect for everyday casual wear and walking.",
    discount: 80,
    price: 29.99,
    listPrice: 39.99,
    images: [
      "https://m.media-amazon.com/images/I/61xeemurkoL._SY500_.jpg", // stylish women sneakers
      "https://m.media-amazon.com/images/I/61hXGcQXMmL._SY500_.jpg",
    ],
    gender: "Women",
    category: "Sneakers",
    brand: "EaseWear",
    tags: ["casual", "canvas", "women", "today-deal"],
    isPublished: true,
    avgRating: 4.1,
    numReviews: 6,
    numSales: 17,
    countInStock: 28,
    colors: ["grey", "white"],
    sizes: ["S", "M", "L"],
    gender: "Women",
    reviews: [],
  },

  {
    id: 202,
    name: "Fashionable Slip-On Ballet & Casual Bellies Everyday Stylish & Durable Classic Design Ballet Flats Ballerinas for Women's & Girl's HF1402",
    slug: "classic-ballet-flats-women-slip-belives",
    description:
      "Elegant and comfortable ballet flats for daily wear and office styling.",
    discount: 70,
    price: 35.5,
    listPrice: 45.0,
    images: [
      "https://m.media-amazon.com/images/I/61vYvoETE0L._SY500_.jpg",
      "https://m.media-amazon.com/images/I/51Y+20SVRoL._SY500_.jpg",
    ],
    gender: "Women",
    category: "Flats",
    brand: "FemStyle",
    tags: ["flats", "classic", "comfortable", "today-deal"],
    isPublished: true,
    avgRating: 4.4,
    numReviews: 10,
    numSales: 25,
    countInStock: 50,
    colors: ["black", "beige"],
    sizes: ["S", "M", "L", "XL"],
    gender: "Women",
    reviews: [],
  },

  {
    id: 203,
    name: "Women Alexa Running Shoes",
    slug: "sporty-running-shoes-women-alexa",
    description:
      "Lightweight running shoes with great grip and cushioning for active lifestyles.",
    discount: 80,
    price: 49.99,
    listPrice: 60.0,
    images: [
      "https://m.media-amazon.com/images/I/516x4VqF5GL._SY675_.jpg",
      "https://m.media-amazon.com/images/I/61xJ4x87GJL._SY500_.jpg",
    ],
    gender: "Women",
    category: "Sneakers",
    brand: "ActivePro",
    tags: ["running", "sport", "fitness", "today-deal"],
    isPublished: true,
    avgRating: 4.7,
    numReviews: 18,
    numSales: 40,
    countInStock: 40,
    colors: ["pink", "white", "grey"],
    sizes: ["S", "M", "L", "XL"],
    gender: "Women",
    reviews: [],
  },

  {
    id: 204,
    name: " Loafers for Women | Comfortable & Stylish Block Heeled | Fashion Moccasins with Footpharma Footbed | Perfect for Casual, Formal Shoe",
    slug: "elegant-heeled-sandals-women-sandles-for-women-loffers",
    description:
      "Stylish heeled sandals perfect for parties or evening outings.",
    discount: 60,
    price: 59.99,
    listPrice: 75.0,
    images: [
      "https://m.media-amazon.com/images/I/61aIyIcz4fL._SY500_.jpg",
      "https://m.media-amazon.com/images/I/6175BMTCMoL._SY500_.jpg",
    ],
    gender: "Women",
    category: "Footwear",
    brand: "GlamourStep",
    tags: ["heels", "party", "elegant"],
    isPublished: true,
    avgRating: 4.6,
    numReviews: 12,
    numSales: 22,
    countInStock: 30,
    colors: ["red", "black"],
    sizes: ["M", "L", "XL"],
    gender: "Women",
    reviews: [],
  },
  {
    id: 2040,
    name: "YOHO Bliss 007 Slip-on Loafers for Women | Comfortable & Stylish Flat | Fashion Moccasins with Footpharma Footbed | Perfect for Casual, Formal Shoe",
    slug: "elegant-heeled-sandals-women-sandles-for-women-loffers-women-shoes",
    description:
      "Stylish heeled sandals perfect for parties or evening outings.",
    discount: 30,
    price: 49.99,
    listPrice: 75.0,
    images: [
      "https://m.media-amazon.com/images/I/61G5rifrdFL._SY500_.jpg",
      "https://m.media-amazon.com/images/I/61aGBtWc9qL._SY500_.jpg",
    ],
    gender: "Women",
    category: "Footwear",
    brand: "GlamourStep",
    tags: ["heels", "party", "elegant", "today-deal"],
    isPublished: true,
    avgRating: 4.6,
    numReviews: 12,
    numSales: 22,
    countInStock: 30,
    colors: ["red", "black"],
    sizes: ["M", "L", "XL"],
    gender: "Women",
    reviews: [],
  },

  {
    id: 205,
    name: "Doctor Walk Women's Comfort Slip-On Loafers, Black Leather, Low Wedge Heel Bellies",
    slug: "comfy-slip-on-loafers-women-leather",
    description:
      "Soft slip-on loafers designed for comfort and casual office looks.",
    discount: 70,
    price: 42.0,
    listPrice: 50.0,
    images: [
      "https://m.media-amazon.com/images/I/71vO1UM63iL._SY500_.jpg",
      "https://m.media-amazon.com/images/I/81aoj5RJHtL._SY500_.jpg",
    ],
    gender: "Women",
    category: "Footwear",
    brand: "UrbanWalk",
    tags: ["loafers", "today-deal"],
    isPublished: true,
    avgRating: 4.2,
    numReviews: 9,
    numSales: 15,
    countInStock: 35,
    colors: ["brown", "black"],
    sizes: ["S", "M", "L"],
    gender: "Women",
    reviews: [],
  },
  {
    id: 301,
    name: "VINCENT CHASE EYEWEAR By Lenskart | Full Rim Cateye | Economic Range | Branded Latest And Stylish Polarized Sunglasses | 100% Uv Protected | Women's | Vc S15798",
    slug: "stylish-sunglasses-women-lenskart",
    description:
      "Trendy and UV-protected sunglasses perfect for sunny days and beach outings.",
    discount: 30,
    price: 49.99,
    listPrice: 95.0,
    images: [
      "https://m.media-amazon.com/images/I/51kK+tz-KvL._SX679_.jpg",
      "https://m.media-amazon.com/images/I/61S5o9smoEL._SY679_.jpg",
    ],
    gender: "Women",
    category: "Accessories",
    brand: "SunChic",
    tags: ["sunglasses", "fashion", "today-deal"],
    isPublished: true,
    avgRating: 4.5,
    numReviews: 14,
    numSales: 30,
    countInStock: 40,
    colors: ["black", "brown"],
    sizes: [],
    gender: "Women",
    reviews: [],
  },
  {
    id: 3010,
    name: "Full Rim Square Polarized Sunglasses| 100% Uv Protected | Men & Women | Vc S14088",
    slug: "stylish-sunglasses-women-sunglasses",
    description:
      "Trendy and UV-protected sunglasses perfect for sunny days and beach outings.",
    discount: 90,
    price: 49.99,
    listPrice: 95.0,
    images: [
      "https://m.media-amazon.com/images/I/41xXYvjCdyL._SX679_.jpg",
      "https://m.media-amazon.com/images/I/519GMvo9tqL.jpg",
    ],
    gender: "Women",
    category: "Accessories",
    brand: "SunChic",
    tags: ["sunglasses", "fashion", "today-deal"],
    isPublished: true,
    avgRating: 4.5,
    numReviews: 14,
    numSales: 30,
    countInStock: 40,
    colors: ["black", "brown"],
    sizes: [],
    gender: "Women",
    reviews: [],
  },

  {
    id: 302,
    name: "HIGH TOUCH Leather Scarlett Women's Handbag/Shoulder Bag",
    slug: "leather-handbag-women-scarlet",
    description:
      "Elegant and spacious leather handbag designed for daily use and special occasions.",
    discount: 70,
    price: 79.99,
    listPrice: 95.0,
    images: [
      "https://m.media-amazon.com/images/I/91PORHaaBUL._SY500_.jpg",
      "https://m.media-amazon.com/images/I/81ZERwn3qbL._SY535_.jpg",
    ],
    gender: "Women",
    category: "Handbags",
    brand: "UrbanStyle",
    tags: ["handbag", "today-deal", "fashion"],
    isPublished: true,
    avgRating: 4.7,
    numReviews: 20,
    numSales: 25,
    countInStock: 25,
    colors: ["black", "tan"],
    sizes: [],
    gender: "Women",
    reviews: [],
  },
  {
    id: 3020,
    name: "Lavie Luxe Women's Cob's 25 Medium Solid Satchel Handbag for Women | Satchel Bag for Work | Ladies purse | Stylish Shoulder Bag | Ladies Gift",
    slug: "leather-handbag-women-scarlet-handbag",
    description:
      "Elegant and spacious leather handbag designed for daily use and special occasions.",
    discount: 60,
    price: 79.99,
    listPrice: 95.0,
    images: [
      "https://m.media-amazon.com/images/I/71U++aoO+cL._SY500_.jpg",
      "https://m.media-amazon.com/images/I/81IJTHuZlaL._SY500_.jpg",
    ],
    gender: "Women",
    category: "Handbags",
    brand: "UrbanStyle",
    tags: ["handbag", "today-deal", "fashion"],
    isPublished: true,
    avgRating: 4.7,
    numReviews: 20,
    numSales: 25,
    countInStock: 25,
    colors: ["black", "tan"],
    sizes: [],
    gender: "Women",
    reviews: [],
  },

  // Men Accessories
  {
    id: 303,
    name: "Bacca Bucci® Men's Reversible Classic Dress Belt Italian Top Grain Genuine Leather Black & Brown with Rotating Metal Buckle-Black/Brown",
    slug: "classic-leather-belt-men-brown",
    description:
      "Durable and stylish leather belt suitable for formal and casual wear.",
    discount: 30,
    price: 65.0,
    listPrice: 45.0,
    images: [
      "https://m.media-amazon.com/images/I/61s1etnxiUL._SX679_.jpg",
      "https://m.media-amazon.com/images/I/6110zfAb-rL._SX679_.jpg",
    ],
    gender: "Men",
    category: "Accessories",
    brand: "Gentleman's Choice",
    tags: ["belt", "today-deal", "classic"],
    isPublished: true,
    avgRating: 4.6,
    numReviews: 12,
    numSales: 22,
    countInStock: 50,
    colors: ["brown", "black"],
    sizes: [],
    gender: "Men",
    reviews: [],
  },

  {
    id: 304,
    name: "Titan Karishma Analog Black Dial Men's Watch NM1639SM02/NN1639SM02",
    slug: "mens-wristwatch-titan",
    description:
      "Elegant wristwatch with leather strap and analog display for everyday style.",
    discount: 60,
    price: 129.99,
    listPrice: 150.0,
    images: [
      "https://m.media-amazon.com/images/I/51ykbSj-eoL._SX679_.jpg",
      "https://m.media-amazon.com/images/I/51iBYW8bvPL._SX679_.jpg",
    ],
    gender: "Women",
    category: "Watches",
    brand: "Titan",
    tags: ["watch", "today-deal", "analog"],
    isPublished: true,
    avgRating: 4.8,
    numReviews: 30,
    numSales: 45,
    countInStock: 30,
    colors: ["black", "brown"],
    sizes: [],
    gender: "Men",
    reviews: [],
  },

  {
    id: 305,
    name: "Puma Men's Cap",
    slug: "casual-cap-men-puma",
    description:
      "Breathable cotton cap perfect for casual outings and sports activities.",
    discount: 50,
    price: 19.99,
    listPrice: 25.0,
    images: [
      "https://m.media-amazon.com/images/I/51zDQyDoV0L._SX679_.jpg",
      "https://m.media-amazon.com/images/I/51hBciQhASL._SX679_.jpg",
    ],
    gender: "Men",
    category: "Accessories",
    brand: "SportyGear",
    tags: ["cap", "cotton", "casual"],
    isPublished: true,
    avgRating: 4.3,
    numReviews: 10,
    numSales: 18,
    countInStock: 60,
    colors: ["blue", "grey", "black"],
    sizes: [],
    gender: "Men",
    reviews: [],
  },
  {
    id: 306,
    name: "ANEZKA Cap for Men Women Topi Unisex Head Branded Boy's Girl's Caps Adjustable Strap Summer Sports Cricket Gym Dance Cotton Free Size Woolen Fashion Baseball Hip hop",
    slug: "casual-cap-men-puma-hip",
    description:
      "Breathable cotton cap perfect for casual outings and sports activities.",
    discount: 60,
    price: 59.99,
    listPrice: 99.0,
    images: [
      "https://m.media-amazon.com/images/I/81C6Gpb6KpL._SX679_.jpg",
      "https://m.media-amazon.com/images/I/81SYrxQyISL._SX679_.jpg",
    ],
    gender: "Men",
    category: "Accessories",
    brand: "SportyGear",
    tags: ["cap", "today-deal", "casual"],
    isPublished: true,
    avgRating: 4.3,
    numReviews: 10,
    numSales: 18,
    countInStock: 60,
    colors: ["blue", "grey", "black"],
    sizes: [],
    gender: "Men",
    reviews: [],
  },
];
